### ISSUE TITLE
Possibility to add text ?

### ISSUE THREAD

**Issue by kohaistyle** [garfix/movemegif#1]
Hi, and firstly, thanks for your lib, and sharing it with us.

Being based on GD, wondered how one could add some text layer on the gif ?

It could help us if you had an exemple somewhere ?

Anyway, keep up the good work.

**Comment by garfix** [comment]
Hi. You're welcome. I hope you enjoy it.

You can use any of PHP's GD functions. "pong.php" provides an example that uses GD directly, but it's not very easy to understand. I made an simpler example for you with GD that shows how to draw text:

(include autoloader.php first)

```
use movemegif\domain\GdCanvas;
use movemegif\GifBuilder;

$builder = new GifBuilder(500, 200);
$builder->setRepeat(0);

$frameCount = 110;
for ($i = 0; $i < $frameCount; $i++) {

    $y = ($i < $frameCount / 2) ? $i : $frameCount - $i;

    $canvas = new GdCanvas(500, 200);

    $im = $canvas->getResource();

    $textColor = imagecolorallocate($im, 233, 14, 91);
    $bgColor = imagecolorallocate($im, 0, 200, 0);

    imagefilledrectangle($im, 0, 0, 500, 200, $bgColor);
    imagestring($im, 5, 5, $y * 3 + 5,  'A Simple Text String', $textColor);

    $builder->addFrame()->setCanvas($canvas)->setDuration(5);
}

$builder->output('text.gif');

```
